// default package
// Generated Oct 26, 2014 11:32:48 PM by Hibernate Tools 3.6.0
package org.mum.scrum.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.Valid;
import org.mum.scrum.util.GlobalVar;
/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "sec_user_roles", catalog = GlobalVar.db_name)
public class EmployeeRole implements java.io.Serializable {

	private Integer employeeRoleId;	
	private Role role;
	@Valid
	private Employee employee;
	private Date createDate;
	private Date updateDate;
	private Date deleteDate;
	private String operator;

	public EmployeeRole() {
	}

	public EmployeeRole(Role role, Employee user) {
		this.role = role;
		this.employee = user;
	}

	public EmployeeRole(Role role, Employee user, Date createDate, Date updateDate,
			Date deleteDate) {
		this.role = role;
		this.employee = user;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.deleteDate = deleteDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_role_id", unique = true, nullable = false)
	public Integer getEmployeeRoleId() {
		return this.employeeRoleId;
	}

	public void setEmployeeRoleId(Integer userRoleId) {
		this.employeeRoleId = userRoleId;
	}

	@ManyToOne
	@JoinColumn(name = "role_id", nullable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne
	@JoinColumn(name = "username", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee user) {
		this.employee = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_date", length = 19)
	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

	@Column(name = "operator", length = 45)
	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

}
