package org.mum.scrum.entities;

// Generated Oct 21, 2014 10:30:35 AM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;

import org.mum.scrum.util.GlobalVar;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "sec_roles", catalog = GlobalVar.db_name)
public class Role implements java.io.Serializable {

	private Integer roleId;
	@Size(min=1,message="Role Name is required.")
	private String roleName;
	private String roleDesc;
	private Date createDate;
	private Date updateDate;
	private String operator;
	private Byte roleLV;
	private Byte status;
	private Set<EmployeeRole> userRoles = new HashSet<EmployeeRole>(0);

	public Role() {
	}

	public Role(String roleName, String roleDesc, Date createDate,
			Date updateDate, Byte status, Set<EmployeeRole> userRoles) {
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.status = status;
		this.userRoles = userRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc")
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "operator", length = 45)
	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "role_lv")
	public Byte getRoleLV() {
		return roleLV;
	}

	public void setRoleLV(Byte roleLV) {
		this.roleLV = roleLV;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<EmployeeRole> getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set<EmployeeRole> userRoles) {
		this.userRoles = userRoles;
	}


}
